language: php

cache: vendor

php:
  - 7.1
  - 7.2

before_script:
  - pear install PHP_CodeSniffer
  - pear install phpDocumentor
  - composer install

script:
  - vendor/bin/grumphp run
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)