language: php

cache: vendor

php:
  - 7.1
  - 7.2

before_script:
  - pear install PHP_CodeSniffer
  - pear install phpDocumentor
  #- sudo wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O /php-cs-fixer
  #- sudo chmod +x /php-cs-fixer
  #- sudo mv /php-cs-fixer /usr/local/bin/
  - sudo wget https://phar.phpunit.de/phpunit-6.4.phar
  - sudo chmod +x phpunit-6.4.phar
  - sudo mv phpunit-6.4.phar /usr/local/bin/phpunit
  #- sudo chmod +x ./codeclimate.sh
  - composer install

script:
  - vendor/bin/grumphp run
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)